name: project_template
description: Starting template for a new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #* UI
  cached_network_image: ^3.1.0
  flash: ^2.0.3
  flutter_keyboard_visibility: ^5.1.0
  google_fonts: ^2.1.0

  #* Icons
  flutter_vector_icons: ^1.0.0

  #* Firebase
  firebase_analytics: ^8.3.3
  firebase_core: ^1.7.0
  firebase_crashlytics: ^2.2.3
  firebase_messaging: ^10.0.8

  #* Local notification
  awesome_notifications: ^0.0.6+11

  #* Network
  dio: ^4.0.0
  pretty_dio_logger: ^1.2.0-beta-1

  #* Dart data class
  freezed_annotation: ^0.15.0
  json_annotation: ^4.3.0

  #* Dependency injection
  get_it: ^7.2.0
  injectable: ^1.5.0

  #* State management
  bloc_concurrency: ^0.2.0-dev.1
  flutter_bloc: ^8.0.0-dev.2
  flutter_hooks: ^0.18.0

  #* Logging
  logging: ^1.0.2

  #* Routing
  auto_route: ^2.4.2

  #* Persistent storage
  flutter_secure_storage: ^4.2.1
  hive_flutter: ^1.1.0

  #* Localization
  easy_localization: ^3.0.0

  #* Date Time util
  jiffy: ^4.1.0

  #* Misc
  dartz: ^0.10.0
  money2: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  #* Code generators
  auto_route_generator: ^2.4.1
  build_runner: ^2.1.4
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.4
  freezed: ^0.15.0+1
  injectable_generator: ^1.5.2
  json_serializable: ^6.0.0

  #* test
  mocktail: ^0.2.0
  bloc_test: ^9.0.0-dev.3

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    # Translation folder path containing .json files
    # run in terminal to generate localization keys:
    # flutter pub run easy_localization:generate -f keys -S assets/translations -O lib/extra/langs -o locale_keys.g.dart
    - assets/translations/