name: project_template
description: Starting template for a new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #* UI
  cached_network_image: ^3.3.0
  flash: ^3.1.0
  flutter_keyboard_visibility: ^5.4.1
  google_fonts: ^6.1.0

  #* Icons
  flutter_vector_icons: ^2.0.0

  #* Firebase
  firebase_analytics: ^10.7.2
  firebase_core: ^2.24.0
  firebase_crashlytics: ^3.4.6
  firebase_messaging: ^14.7.6

  #* Local notification
  awesome_notifications: ^0.8.2

  #* Network
  dio: ^5.3.4
  pretty_dio_logger: ^1.3.1

  #* Dart data class
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  #* Dependency injection
  get_it: ^7.6.4
  injectable: ^2.3.2

  #* State management
  bloc_concurrency: ^0.2.2
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.20.3

  #* Logging
  logging: ^1.2.0

  #* Routing
  auto_route: ^7.8.4

  #* Persistent storage
  flutter_secure_storage: ^9.0.0
  hive_flutter: ^1.1.0

  #* Localization
  intl: ^0.18.1

  #* Date Time util
  jiffy: ^6.2.1

  #* Misc
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  #* Code generators
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.6
  freezed: ^2.4.5
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

  #* Test
  bloc_test: ^9.1.5
  mocktail: ^1.0.1

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true