name: project_template
description: Starting template for a new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #* UI
  cached_network_image: ^3.2.0
  flash: ^2.0.3+2
  flutter_keyboard_visibility: ^5.1.1
  google_fonts: ^2.3.1

  #* Icons
  flutter_vector_icons: ^1.0.0

  #* Firebase
  firebase_analytics: ^9.1.0
  firebase_core: ^1.12.0
  firebase_crashlytics: ^2.5.0
  firebase_messaging: ^11.2.6

  #* Local notification
  awesome_notifications: ^0.6.21

  #* Network
  dio: ^4.0.4
  pretty_dio_logger: ^1.2.0-beta-1

  #* Dart data class
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0

  #* Dependency injection
  get_it: ^7.2.0
  injectable: ^1.5.3

  #* State management
  bloc_concurrency: ^0.2.0
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.2

  #* Logging
  logging: ^1.0.2

  #* Routing
  auto_route: ^3.2.2

  #* Persistent storage
  flutter_secure_storage: ^5.0.2
  hive_flutter: ^1.1.0

  #* Localization
  easy_localization: ^3.0.0

  #* Date Time util
  jiffy: ^5.0.0

  #* Misc
  dartz: ^0.10.1
  money2: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  #* Code generators
  auto_route_generator: ^3.2.1
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.0.1+1
  freezed: ^1.1.0
  injectable_generator: ^1.5.2
  json_serializable: ^6.1.4

  #* test
  mocktail: ^0.2.0
  bloc_test: ^9.0.2

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    # Translation folder path containing .json files
    # run in terminal to generate localization keys:
    # flutter pub run easy_localization:generate -f keys -S assets/translations -O lib/extra/langs -o locale_keys.g.dart
    - assets/translations/